require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 4
RSpec/NestedGroups:
  Max: 7
RSpec/ExampleLength:
  Max: 20
