#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
Bundler.setup(:default, :development)

require 'pry'
require './lib/system/app_container'
require './lib/dry_robot/bootstrap'
AppContainer.finalize!

Pry.start
